name: Android CI

on:
  push:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Install npm dependencies
      run: |
        npm install
    - name: Prebuild React Native
      run: |
        npx expo prebuild
    - name: Build Android Release
      run: |
        npx react-native build-android --mode=release
    - name: Upload Artifact
      uses: actions/upload-artifact@v1
      with:
        name: app-release.apk
        path: android/app/build/outputs/apk/release/
